// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class User_Account_Model_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Account_Model_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211602142_User_Account_Model_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
